/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.consummigrest;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import retrofit2.Call;
import retrofit2.Response;

/**
 *
 * @author ro
 */
public class Category extends javax.swing.JInternalFrame {

    /**
     * Creates new form Category
     */
    public Category() {
        initComponents();
        listCategory();
    }

    /*public static void main(String[] args) {
        Category form = new Category();
        form.setVisible(true);
    }*/
    private void listCategory() {

        List<CategoryRs> lista = new ArrayList<>();

        try {
            lista = doInBackground();
        } catch (Exception ex) {
            Logger.getLogger(Category.class.getName()).log(Level.SEVERE, null, ex);
        }

        String cabecera[] = {"ID", "NOMBRE"};
        DefaultTableModel table = new DefaultTableModel(null, cabecera);
        String[] registros = new String[2];
        for (CategoryRs response : lista) {
            registros[0] = String.valueOf(response.getCategoryid());
            registros[1] = response.getName();

            table.addRow(registros);
        }
        tbCategory.setModel(table);
    }

    protected List<CategoryRs> doInBackground() throws Exception {
        CategoryService categoryService = RetrofitClient.getClient("http://localhost:9080").create(CategoryService.class);
        Call<List<CategoryRs>> call = categoryService.getAllCategories();
        Response<List<CategoryRs>> response = call.execute();

        return response.body();
    }

    protected void save(CategoryRs categoryRs) throws Exception {
        CategoryService categoryService = RetrofitClient.getClient("http://localhost:9080").create(CategoryService.class);
        Call<HttpStatus> call = categoryService.save(categoryRs);
        call.execute();

    }

    protected void delete(int id) throws Exception {
        CategoryService categoryService = RetrofitClient.getClient("http://localhost:9080").create(CategoryService.class);
        Call<HttpStatus> call = categoryService.delete(id);
        call.execute();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDetail = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        lblId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCategory = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        setClosable(true);

        pnlDetail.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles"));
        pnlDetail.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlDetail.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 240, -1));
        pnlDetail.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 120, 20));

        lblId.setEditable(false);
        pnlDetail.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 190, -1));

        jLabel1.setText("Id:");
        pnlDetail.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setText("Nombre:");
        pnlDetail.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        tbCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tbCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCategoryMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbCategory);

        btnDelete.setText("Eliminar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnModify.setText("Modificar");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        btnAdd.setText("Agregar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(pnlDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnModify)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnModify)
                    .addComponent(btnDelete))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCategoryMouseClicked
        int fila = tbCategory.getSelectedRow();
        String Cod = tbCategory.getValueAt(fila, 0).toString();

        {
            int seleccion = tbCategory.rowAtPoint(evt.getPoint());

            lblId.setText(String.valueOf(tbCategory.getValueAt(seleccion, 0)));
            txtNombre.setText(String.valueOf(tbCategory.getValueAt(seleccion, 1)));

        }
    }//GEN-LAST:event_tbCategoryMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (lblId.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccionar Categoria\na Eliminar", "Atentamente Sistema", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int id = Integer.parseInt(lblId.getText().trim());

        try {
            delete(id);
            JOptionPane.showMessageDialog(null, "Eliminado");
            listCategory();
        } catch (Exception ex) {
            Logger.getLogger(Category.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "ERROR EN REGISTRAR");
        }


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed

        CategoryRs category = new CategoryRs();

        category.setCategoryid(Integer.parseInt(lblId.getText()));
        category.setName(txtNombre.getText());
        try {

            save(category);
            txtNombre.setText("");
            lblId.setText("");
            listCategory();

        } catch (Exception e) {
            Logger.getLogger(Category.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(null, "ERROR EN REGISTRAR");
        }
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        CategoryRs category = new CategoryRs();

        category.setCategoryid(0);
        category.setName(txtNombre.getText());
        try {
            save(category);
            txtNombre.setText("");
            listCategory();

        } catch (Exception e) {
            Logger.getLogger(Category.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(null, "ERROR EN REGISTRAR");
        }
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnModify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lblId;
    public javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlDetail;
    private javax.swing.JTable tbCategory;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

}
